import { FC, ReactNode } from 'react';
import { Divider, Typography, ConfigProvider } from 'antd-v5';

import { t, useTheme } from '@superset-ui/core';
import { useDataWarehouse } from '../../contexts/DataWarehouseContext';
import { useHeader } from '../../contexts/HeaderContext';
import { useComponentInfo } from '../../contexts/ComponentInfoContext';

interface LayoutProps {
  children: ReactNode;
}

const Wrapper: FC<LayoutProps> = ({ children }) => {
  const theme = useTheme();
  const { database, table, alreadyExists } = useDataWarehouse();
  const { active, label } = useHeader();
  const { editMode } = useComponentInfo();

  const isDatabaseReady = database && alreadyExists && table.length > 0;

  return (
    <ConfigProvider
      theme={{
        components: {
          Button: {
            borderColorDisabled: '#d9d9d9',
            contentFontSize: 14,
            contentFontSizeLG: 16,
            contentFontSizeSM: 14,
            contentLineHeight: 1.5714285714285714,
            contentLineHeightLG: 1.5,
            contentLineHeightSM: 1.5714285714285714,
            dangerColor: '#fff',
            dangerShadow: '0 2px 0 rgba(255,38,5,0.06)',
            defaultActiveBg: '#ffffff',
            defaultActiveBorderColor: '#0958d9',
            defaultActiveColor: '#0958d9',
            defaultBg: '#ffffff',
            defaultBorderColor: '#d9d9d9',
            defaultColor: 'rgba(0,0,0,0.88)',
            defaultGhostBorderColor: '#ffffff',
            defaultGhostColor: '#ffffff',
            defaultHoverBg: '#ffffff',
            defaultHoverBorderColor: '#4096ff',
            defaultHoverColor: '#4096ff',
            defaultShadow: '0 2px 0 rgba(0,0,0,0.02)',
            fontWeight: 400,
            ghostBg: 'transparent',
            groupBorderColor: '#4096ff',
            linkHoverBg: 'transparent',
            paddingBlock: 4,
            paddingBlockLG: 7,
            paddingBlockSM: 0,
            paddingInline: 15,
            paddingInlineLG: 15,
            paddingInlineSM: 7,
            primaryColor: '#fff',
            primaryShadow: '0 2px 0 rgba(5,145,255,0.1)',
            textHoverBg: 'rgba(0,0,0,0.04)',
            colorBgContainer: '#ffffff',
            colorBgContainerDisabled: 'rgba(0, 0, 0, 0.04)',
            colorBgTextActive: 'rgba(0, 0, 0, 0.15)',
            colorBorder: '#d9d9d9',
            colorError: '#ff4d4f',
            colorErrorActive: '#d9363e',
            colorErrorBg: '#fff2f0',
            colorErrorBgActive: '#ffccc7',
            colorErrorBorderHover: '#ffa39e',
            colorErrorHover: '#ff7875',
            colorFill: 'rgba(0,0,0,0.15)',
            colorFillSecondary: 'rgba(0,0,0,0.06)',
            colorFillTertiary: 'rgba(0,0,0,0.04)',
            colorInfo: '#1677ff',
            colorInfoActive: '#0958d9',
            colorInfoHover: '#69b1ff',
            colorLink: '#1677ff',
            colorLinkActive: '#0958d9',
            colorLinkHover: '#69b1ff',
            colorPrimary: '#1677ff',
            colorPrimaryActive: '#0958d9',
            colorPrimaryBg: '#e6f4ff',
            colorPrimaryBgHover: '#bae0ff',
            colorPrimaryBorder: '#91caff',
            colorPrimaryHover: '#4096ff',
            colorPrimaryText: '#1677ff',
            colorPrimaryTextActive: '#0958d9',
            colorPrimaryTextHover: '#4096ff',
            colorText: 'rgba(0,0,0,0.88)',
            colorTextDisabled: 'rgba(0,0,0,0.25)',
            colorTextLightSolid: '#fff',
            borderRadius: 6,
            borderRadiusLG: 8,
            borderRadiusSM: 32,
            controlHeightLG: 40,
            controlHeightSM: 24,
            fontSize: 14,
            lineType: 'solid',
            lineWidth: 1,
            lineWidthFocus: 3,
            marginXS: 8,
            motionDurationMid: '0.2s',
            motionDurationSlow: '0.3s',
            motionEaseInOut: 'cubic-bezier(0.645, 0.045, 0.355, 1)',
            opacityLoading: 0.65,
            paddingXS: 8,
          },
          Input: {
            activeBg: '#ffffff',
            activeBorderColor: '#1677ff',
            activeShadow: '0 0 0 2px rgba(5,145,255,0.1)',
            addonBg: 'rgba(0,0,0,0.02)',
            errorActiveShadow: '0 0 0 2px rgba(255,38,5,0.06)',
            hoverBg: '#ffffff',
            hoverBorderColor: '#4096ff',
            inputFontSize: 14,
            inputFontSizeLG: 16,
            inputFontSizeSM: 14,
            paddingBlock: 4,
            paddingBlockLG: 7,
            paddingBlockSM: 0,
            paddingInline: 11,
            paddingInlineLG: 11,
            paddingInlineSM: 7,
            warningActiveShadow: '0 0 0 2px rgba(255,215,5,0.1)',
            colorBgContainer: '#ffffff',
            colorBgContainerDisabled: 'rgba(0,0,0,0.04)',
            colorBorder: '#d9d9d9',
            colorError: '#ff4d4f',
            colorErrorBg: '#fff2f0',
            colorErrorText: '#ff4d4f',
            colorFillTertiary: 'rgba(0,0,0,0.04)',
            colorPrimaryActive: '#0958d9',
            colorPrimaryHover: '#4096ff',
            colorText: 'rgba(0,0,0,0.88)',
            colorTextDescription: 'rgba(0,0,0,0.45)',
            colorTextDisabled: 'rgba(0,0,0,0.25)',
            colorWarning: '#faad14',
            colorWarningBg: '#fffbe6',
            colorWarningText: '#faad14',
            borderRadius: 6,
            borderRadiusLG: 8,
            borderRadiusSM: 4,
            controlHeight: 32,
            controlHeightLG: 40,
            controlHeightSM: 24,
            fontFamily:
              "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
            fontSize: 14,
            lineHeight: 1.5714285714285714,
            lineHeightLG: 1.5,
            lineType: 'solid',
            lineWidth: 1,
            motionDurationSlow: '0.3s',
            paddingXS: 8,
            paddingXXS: 4,
          },
          Select: {
            colorPrimaryHover: '#4096ff',
            clearBg: '#ffffff',
            multipleItemBg: 'rgba(0,0,0,0.06)',
            multipleItemBorderColor: 'transparent',
            multipleItemBorderColorDisabled: 'transparent',
            multipleItemColorDisabled: 'rgba(0,0,0,0.25)',
            multipleItemHeight: 24,
            multipleItemHeightLG: 32,
            multipleItemHeightSM: 16,
            multipleSelectorBgDisabled: 'rgba(0,0,0,0.04)',
            optionActiveBg: 'rgba(0,0,0,0.04)',
            optionFontSize: 14,
            optionHeight: 32,
            optionLineHeight: 1.5714285714285714,
            optionPadding: '5px 12px',
            optionSelectedBg: '#e6f4ff',
            optionSelectedColor: 'rgba(0,0,0,0.88)',
            optionSelectedFontWeight: 600,
            selectorBg: '#ffffff',
            showArrowPaddingInlineEnd: 18,
            singleItemHeightLG: 40,
            zIndexPopup: 1050,
            colorBgBase: '#fff',
            colorBgContainer: '#ffffff',
            colorBgContainerDisabled: 'rgba(0,0,0,0.04)',
            colorBgElevated: '#ffffff',
            colorBorder: '#d9d9d9',
            colorError: '#ff4d4f',
            colorErrorBg: '#fff2f0',
            colorErrorBgHover: '#fff1f0',
            colorErrorHover: '#ff7875',
            colorErrorOutline: 'rgba(255,38,5,0.06)',
            colorFillSecondary: 'rgba(0,0,0,0.06)',
            colorFillTertiary: 'rgba(0,0,0,0.04)',
            colorIcon: 'rgba(0,0,0,0.45)',
            colorIconHover: 'rgba(0,0,0,0.88)',
            colorPrimary: '#1677ff',
            colorSplit: 'rgba(5,5,5,0.06)',
            colorText: 'rgba(0,0,0,0.88)',
            colorTextDescription: 'rgba(0,0,0,0.45)',
            colorTextDisabled: 'rgba(0,0,0,0.25)',
            colorTextPlaceholder: 'rgba(0,0,0,0.25)',
            colorTextQuaternary: 'rgba(0,0,0,0.25)',
            colorWarning: '#faad14',
            colorWarningBg: '#fffbe6',
            colorWarningBgHover: '#fff1b8',
            colorWarningHover: '#ffd666',
            colorWarningOutline: 'rgba(255,215,5,0.1)',
            hoverBorderColor: '#4096ff',
            borderRadius: 6,
            borderRadiusLG: 8,
            borderRadiusSM: 4,
            borderRadiusXS: 2,
            boxShadowSecondary:
              '0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)',
            controlHeight: 32,
            controlHeightLG: 40,
            controlHeightSM: 24,
            controlOutlineWidth: 2,
            controlPaddingHorizontal: 12,
            controlPaddingHorizontalSM: 8,
            fontFamily:
              "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
            fontSize: 14,
            fontSizeIcon: 12,
            fontSizeLG: 16,
            fontSizeSM: 12,
            lineHeight: 1.5714285714285714,
            lineType: 'solid',
            lineWidth: 1,
            motionDurationMid: '0.2s',
            motionDurationSlow: '0.3s',
            motionEaseInOut: 'cubic-bezier(0.645, 0.045, 0.355, 1)',
            motionEaseInOutCirc: 'ubic-bezier(0.78, 0.14, 0.15, 0.86)',
            motionEaseInQuint: 'cubic-bezier(0.755, 0.05, 0.855, 0.06)',
            motionEaseOutCirc: 'cubic-bezier(0.08, 0.82, 0.17, 1)',
            motionEaseOutQuint: 'cubic-bezier(0.23, 1, 0.32, 1)',
            paddingSM: 12,
            paddingXS: 8,
            paddingXXS: 4,
          },
          Switch: {
            handleBg: '#fff',
            handleShadow: '0 2px 4px 0 rgba(0,35,11,0.2)',
            handleSize: 18,
            handleSizeSM: 12,
            innerMaxMargin: 24,
            innerMaxMarginSM: 18,
            innerMinMargin: 9,
            innerMinMarginSM: 6,
            trackHeight: 22,
            trackHeightSM: 16,
            trackMinWidth: 44,
            trackMinWidthSM: 28,
            trackPadding: 2,
            colorPrimary: '#1677ff',
            colorPrimaryBorder: '#91caff',
            colorPrimaryHover: '#4096ff',
            colorText: 'rgba(0,0,0,0.88)',
            colorTextLightSolid: '#fff',
            colorTextQuaternary: 'rgba(0,0,0,0.25)',
            colorTextTertiary: 'rgba(0,0,0,0.45)',
            fontFamily:
              "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
            fontSize: 14,
            fontSizeIcon: 12,
            fontSizeSM: 12,
            lineHeight: 1.5714285714285714,
            lineWidthFocus: 3,
            marginXXS: 4,
            motionDurationMid: '0.2s',
            opacityLoading: 0.65,
          },
          Modal: {
            contentBg: '#ffffff',
            footerBg: 'transparent',
            headerBg: '#ffffff',
            titleColor: 'rgba(0,0,0,0.88)',
            titleFontSize: 16,
            titleLineHeight: 1.5,
            colorBgMask: 'rgba(0,0,0,0.45)',
            colorBgTextActive: 'rgba(0,0,0,0.15)',
            colorBgTextHover: 'rgba(0,0,0,0.06)',
            colorIcon: 'rgba(0,0,0,0.45)',
            colorIconHover: 'rgba(0,0,0,0.88)',
            colorPrimaryBorder: '#91caff',
            colorSplit: 'rgba(5,5,5,0.06)',
            colorText: 'rgba(0,0,0,0.88)',
            borderRadiusLG: 8,
            borderRadiusSM: 4,
            boxShadow:
              '0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)',
            controlHeight: 32,
            fontFamily:
              "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
            fontSize: 14,
            fontSizeHeading5: 16,
            fontSizeLG: 16,
            fontWeightStrong: 600,
            lineHeight: 1.5714285714285714,
            lineHeightHeading5: 1.5,
            lineType: 'solid',
            lineWidth: 1,
            lineWidthFocus: 3,
            margin: 16,
            marginXS: 8,
            motionDurationMid: '0.2s',
            motionDurationSlow: '0.3s',
            motionEaseInOutCirc: 'cubic-bezier(0.78, 0.14, 0.15, 0.86)',
            motionEaseOutCirc: 'cubic-bezier(0.08, 0.82, 0.17, 1)',
            padding: 16,
            paddingLG: 24,
            screenLGMin: 992,
            screenMDMin: 768,
            screenSMMax: 767,
            screenSMMin: 576,
            screenXLMin: 1200,
            screenXSMin: 480,
            screenXXLMin: 1600,
            zIndexPopupBase: 1000,
          },
          Tooltip: {
            zIndexPopup: 1070,
            colorBgSpotlight: 'rgba(0,0,0,0.85)',
            colorText: 'rgba(0,0,0,0.88)',
            colorTextLightSolid: '#fff',
            borderRadius: 6,
            borderRadiusXS: 2,
            boxShadowSecondary:
              '0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)',
            controlHeight: 32,
            fontFamily:
              "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
            fontSize: 14,
            lineHeight: 1.5714285714285714,
            motionDurationFast: '0.1s',
            motionEaseInOutCirc: 'cubic-bezier(0.78, 0.14, 0.15, 0.86)',
            motionEaseOutCirc: 'cubic-bezier(0.08, 0.82, 0.17, 1)',
            paddingSM: 12,
            paddingXS: 8,
            sizePopupArrow: 16,
          },
          Form: {
            inlineItemMarginBottom: 0,
            itemMarginBottom: 24,
            labelColonMarginInlineEnd: 8,
            labelColonMarginInlineStart: 2,
            labelColor: 'rgba(0,0,0,0.88)',
            labelFontSize: 14,
            labelHeight: 32,
            labelRequiredMarkColor: '#ff4d4f',
            verticalLabelMargin: 0,
            verticalLabelPadding: '0 0 8px',
            colorBorder: '#d9d9d9',
            colorError: '#ff4d4f',
            colorPrimary: '#1677ff',
            colorSuccess: '#52c41a',
            colorText: 'rgba(0,0,0,0.88)',
            colorTextDescription: 'rgba(0,0,0,0.45)',
            colorWarning: '#faad14',
            controlHeight: 32,
            controlHeightLG: 40,
            controlHeightSM: 24,
            controlOutline: 'rgba(5,145,255,0.1)',
            controlOutlineWidth: 2,
            fontFamily:
              "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
            fontSize: 14,
            fontSizeLG: 16,
            lineHeight: 1.5714285714285714,
            lineType: 'solid',
            lineWidth: 1,
            margin: 16,
            marginLG: 24,
            marginXXS: 4,
            motionDurationFast: '0.1s',
            motionDurationMid: '0.2s',
            motionEaseInOut: 'cubic-bezier(0.645, 0.045, 0.355, 1)',
            motionEaseOut: 'cubic-bezier(0.215, 0.61, 0.355, 1)',
            motionEaseOutBack: 'cubic-bezier(0.12, 0.4, 0.29, 1.46)',
            paddingSM: 12,
            screenLGMax: 1199,
            screenMDMax: 991,
            screenSMMax: 767,
            screenXSMax: 575,
          },
          Divider: {
            orientationMargin: 0.05,
            textPaddingInline: '1em',
            verticalMarginInline: 8,
            colorSplit: 'rgba(5,5,5,0.06)',
            colorText: 'rgba(0,0,0,0.88)',
            colorTextHeading: 'rgba(0,0,0,0.88)',
            fontFamily:
              "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
            fontSize: 14,
            fontSizeLG: 16,
            lineHeight: 1.5714285714285714,
            lineWidth: 1,
            margin: 16,
            marginLG: 24,
            marginXS: 8,
          },
          Badge: {
            dotSize: 6,
            indicatorHeight: 20,
            indicatorHeightSM: 14,
            indicatorZIndex: 'auto',
            statusSize: 6,
            textFontSize: 12,
            textFontSizeSM: 12,
            textFontWeight: 'normal',
            colorBorderBg: '#ffffff',
            colorError: '#ff4d4f',
            colorErrorHover: '#ff7875',
            colorInfo: '#1677ff',
            colorSuccess: '#52c41a',
            colorText: 'rgba(0,0,0,0.88)',
            colorTextLightSolid: '#fff',
            colorTextPlaceholder: 'rgba(0,0,0,0.25)',
            colorWarning: '#faad14',
            fontFamily:
              "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
            fontSize: 14,
            lineHeight: 1.5714285714285714,
            lineWidth: 1,
            marginXS: 8,
            motionDurationMid: '0.2s',
            motionDurationSlow: '0.3s',
            motionEaseOutBack: 'cubic-bezier(0.12, 0.4, 0.29, 1.46)',
            paddingXS: 8,
          },
          Collapse: {
            contentBg: '#ffffff',
            contentPadding: '16px 16px',
            headerBg: 'rgba(0,0,0,0.02)',
            headerPadding: '12px 16px',
            colorBorder: '#d9d9d9',
            colorPrimaryBorder: '#91caff',
            colorText: 'rgba(0,0,0,0.88)',
            colorTextDisabled: 'rgba(0,0,0,0.25)',
            colorTextHeading: 'rgba(0,0,0,0.88)',
            borderRadiusLG: 8,
            fontFamily:
              "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
            fontSize: 14,
            fontSizeIcon: 12,
            fontSizeLG: 16,
            lineHeight: 1.5714285714285714,
            lineHeightLG: 1.5,
            lineType: 'solid',
            lineWidth: 1,
            lineWidthFocus: 3,
            marginSM: 12,
            motionDurationMid: '0.2s',
            motionDurationSlow: '0.3s',
            motionEaseInOut: 'cubic-bezier(0.645, 0.045, 0.355, 1)',
            padding: 16,
            paddingLG: 24,
            paddingSM: 12,
            paddingXS: 8,
          },
        },
      }}
    >
      {!editMode && active && (
        <div>
          <Divider style={{ margin: 0 }} orientation="left">
            {label}
          </Divider>
        </div>
      )}
      <div
        style={{
          display: 'flex',
          flexDirection: 'column',
          height: '100%',
          overflow: 'hidden auto',
          gap: '0.5rem',
        }}
      >
        {editMode || isDatabaseReady ? (
          <>{children}</>
        ) : (
          <div
            style={{
              display: 'flex',
              height: '100%',
              justifyContent: 'center',
              alignItems: 'center',
            }}
          >
            <Typography.Text style={{ textAlign: 'center' }} type="secondary">
              {t(
                'Хранилище данных не настроено. Для настройки перейдите в режим редактирования дэшборда.',
              )}
            </Typography.Text>
          </div>
        )}
      </div>
    </ConfigProvider>
  );
};

export default Wrapper;
